export const KEY_PAIR_SUCCESS = "KEY_PAIR_SUCCESS";

export const SET_PHONE = "SET_PHONE";
export const SMS_SUCCESS = "SMS_SUCCESS";
export const SMS_PENDING = "SMS_PENDING";
export const SMS_FAILED = "SMS_FAILED";
export const SET_NAME = "SET_USER_NAME";
export const SEND_TRANSACTIONS = "SEND_TRANSACTIONS";
export const TOGGLE_LOADING_TRANSACTIONS = "TOGGLE_LOADING_TRANSACTIONS";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_PENDING = "AUTH_PENDING";
export const AUTH_FAILED = "AUTH_FAILED";

export const SCREEN_NAME_SUCCESS = "SCREEN_NAME_SUCCESS";

export const PIN_VERIFY_SUCCESS = "PIN_VERIFY_SUCCESS";
export const PIN_VERIFY_FAILED = "PIN_VERIFY_FAILED";

export const WALLET_KEY_SUCCESS = "WALLET_KEY_SUCCESS";
export const WALLET_KEY_FAILED = "WALLET_KEY_FAILED";

export const GET_WALLETS_SUCCESS = "GET_WALLETS_SUCCESS";

export const BUY_TOKENS_SUCCESS = "BUY_TOKENS_SUCCESS";

export const PAIR_WALLET_SUCCESS = "PAIR_WALLET_SUCCESS";
export const PAIR_WALLET_FAILED = "PAIR_WALLET_FAILED";

export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAILED = "GET_CONTACTS_FAILED";

export const TOKEN_CONVERSION_SUCCESS = "TOKEN_CONVERSION_SUCCESS";

export const GET_PAIRED_WEARABLES = "GET_PAIRED_WEARABLES";
export const RESPONSE_PAIR_WEARBLES = "RESPONSE_PAIR_WEARBLES";

export const PROFILE_SUCCESS = "PROFILE_SUCCESS";

export const PROFILE_PICTURE_UPLOAD_SUCCESS = "PROFILE_PICTURE_UPLOAD_SUCCESS";
export const PROFILE_PICTURE_UPLOAD_FAILED = "PROFILE_PICTURE_UPLOAD_FAILED";
export const ENABLE_FACEID = "ENABLE_FACEID";
export const IS_CREW_MODE = "IS_CREW_MODE";

export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAILED = "GET_NOTIFICATIONS_FAILED";
export const VERIFY_RECOVERY_SUCCESS = "VERIFY_RECOVERY_SUCCESS";

export const VERIFY_RECOVERY_SMS_SUCCESS = "VERIFY_RECOVERY_SMS_SUCCESS";
export const VERIFY_RECOVERY_NON_PUBLIC_KEY_SUCCESS =
  "VERIFY_RECOVERY_NON_PUBLIC_KEY_SUCCESS";

export const SET_PASSCODE_RECOVERY_SUCCESS = "SET_PASSCODE_RECOVERY_SUCCESS";

export const RESET_RECOVER_ACCOUNT = "RESET_RECOVER_ACCOUNT";

export const VERIFY_SECURITY_SUCCESS = "VERIFY_SECURITY_SUCCESS";

export const VERIFY_SECURITY_SMS_SUCCESS = "VERIFY_SECURITY_SMS_SUCCESS";

export const RESET_SECURITY_REDUCER = "RESET_SECURITY_REDUCER";

export const FETCH_LOADING = "FETCH_LOADING";
export const GET_NATIONALITY_SUCCESS = "GET_NATIONALITY_SUCCESS";
export const LOADING_PHONE_NUMBER_SCREEN = "LOADING_PHONE_NUMBER_SCREEN";

export const ADD_CONTACTS_EVENTX = "ADD_CONTACTS_EVENTX";
export const ADD_RESET_CONTACTS = "ADD_RESET_CONTACTS";
export const VERIFY_PASS_CODE_EMAIL = "VERIFY_PASS_CODE_EMAIL";
export const RESET_VERIFY_PASS_CODE_EMAIL = "RESET_VERIFY_PASS_CODE_EMAIL";

export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";

export const LOAD_DATA_EVENT = "LOAD_DATA_EVENT";
export const TOGGLE_LOADING_EVENTS = "TOGGLE_LOADING_EVENTS";

export const SET_NUMBER_MY_TICKET = "SET_NUMBER_MY_TICKET";
export const SET_NUMBER_SALE_TICKET = "SET_NUMBER_SALE_TICKET";
export const FOCUS_MY_TICKET = "FOCUS_MY_TICKET";
export const SHOW_SCAN_TICKET = "SHOW_SCAN_TICKET";
export const FOCUS_WALLET = "FOCUS_WALLET";
export const SHOW_TOAST_ACTION = "SHOW_TOAST_ACTION";
