const screenName = {
	HOME_SCREEN: 'HOME_SCREEN',
	LOGIN_SCREEN: 'LOGIN_SCREEN',
	BOTTOM_TAB_STACK: 'BOTTOM_TAB_STACK',
	BOTTOM_TAB_AGENT_STACK: 'BOTTOM_TAB_AGENT_STACK',
	HOME_STACK: 'HOME_STACK',
	NOTIFICATION_STACK: 'NOTIFICATION_STACK',
	PROFILE_STACK: 'PROFILE_STACK',
	DASHBOARD_STACK: 'DASHBOARD_STACK',
};

export default screenName;
