const screenName = {
	HOME_SCREEN: 'HOME_SCREEN',
	LOGIN_SCREEN: 'LOGIN_SCREEN',
	BOTTOM_STACK: 'BOTTOM_STACK',
	HOME_STACK: 'HOME_STACK',
	PROFILE_STACK: 'PROFILE_STACK',
	EXPLORE_STACK: 'EXPLORE_STACK',
};

export default screenName;
